spring.application.name=step11ApplicationProperties
paymentGateway.type=paytm
paymentGateway.retry-count=3

payment-properties.type=phonpe
payment-properties.retry-count=3
payment-properties.isEnabled=true
payment-properties.timeout=3000