spring.application.name=step2security

spring.datasource.url=jdbc:postgresql://localhost:5432/spring1
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=N2s5djh5L0I/RShIK01iUWVUaFdtWnE0dDd3IXolQypGLQ==
jwt.issuer=familia
jwt.expiry=900

#spring.security.user.name=bell
#spring.security.user.password=chan

logging.level.org.springframework.security=TRACE