spring.application.name=step2Cloud

server.port=5000

spring.datasource.url=jdbc:mysql://{DB}/belldb
spring.datasource.username=admin
spring.datasource.password=rootbell

#spring.datasource.url=jdbc:mysql://postgres:5432/bell
#spring.datasource.username=bell
#spring.datasource.password=chan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true