spring.application.name=step5LoggingSpringBoot

logging.level.com.example.step5LoggingSpringBoot.controller=debug

#logging.level.root=trace

logging.pattern.console=%c : %p --> %m :: %d  %n

logging.file.name=logger/log.txt
logging.pattern.file=%d : %c : %p --> %m : %M :  %n