spring.application.name=step1Devops

#spring.datasource.url=jdbc:mysql://localhost:3306/spring6
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.url=jdbc:mysql://postgres:5432/bell
spring.datasource.username=bell
spring.datasource.password=chan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true